<Project>
  <PropertyGroup>
    <BettrFGVersion>2.0.0</BettrFGVersion>
    <BettrFGDisplayName>BettrFG</BettrFGDisplayName>
    <BettrFGInstallerName>BettrFG Installer</BettrFGInstallerName>
    <BettrFGRepoOwner>oreyre9000</BettrFGRepoOwner>
    <BettrFGRepoName>BettrFG</BettrFGRepoName>
    <BettrFGPayloadAssetName>BepInEx.zip</BettrFGPayloadAssetName>
    <KillAndRestartGame Condition="'$(KillAndRestartGame)' == ''">true</KillAndRestartGame>
  </PropertyGroup>
</Project>
